### ISSUE TITLE
Errors from wrangling and data loading

### ISSUE THREAD

**Issue by camadi** [UBC-MDS/DSCI_532_Group114_SKEC#32]
The code below crashes the already working app:

path_pop=x + "Data\Population_trend.csv"
pop_yr = pd.read_csv(path_pop)
pop_yr = pop_yr[['YEAR', 'Population']]

# Reading each neighborhood's proportion of population to overall city's population
path_prop=x + "Data\population_proportion.csv"
pop_prop = pd.read_csv(path_prop)

Should this be backward slash or forward slash? Was the code tested?

**Comment by camadi** [comment]
I have found a workaround by modifying x = x[:len(x)-0] instead of -3

**Comment by vermashivam679** [comment]
Hi, I added 'x = x[:len(x)-3]' because my script was inside `src` folder, this was to get out of src and get inside Data folder to read the data. It worked on my machine... great that its running fine for now...we can resolve these issues when we meet today and work together.

**Comment by chuusan** [comment]
> Hi, I added 'x = x[:len(x)-3]' because my script was inside `src` folder, this was to get out of src and get inside Data folder to read the data. It worked on my machine... great that its running fine for now...we can resolve these issues when we meet today and work together.

Shivam, in my map plot's wrangling, I used a relative path. Please modify that before integrating that into the app.py.
