### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI_532_Group114_SKEC#36]
Hello,
Thanks for your submission of milestone 01. The submission was very clear and structured. I just have some comments for improvement below.
- In your teamwork contract, you need to include the general roles and responsibilities of each team member and the procedure by which new tasks are introduced and assigned.
- There is something that is not clear in the app description. Can users choose multiple neighborhoods and multiple crime types to visualize?
Thanks!

**Comment by chuusan** [comment]
> Hello,
> Thanks for your submission of milestone 01. The submission was very clear and structured. I just have some comments for improvement below.
> 
> * In your teamwork contract, you need to include the general roles and responsibilities of each team member and the procedure by which new tasks are introduced and assigned.
> * There is something that is not clear in the app description. Can users choose multiple neighborhoods and multiple crime types to visualize?
>   Thanks!

Hossan,

Thank you for the feedback. I have updated the general roles/responsibilities of each team member together with other staff in the team contract. Same for the app description.
